// ============================================================
//  Emoji Names Mapping для автокомплита
//  Использование: getEmojiSearchMap() → Map<name, emoji>
// ============================================================

function getEmojiSearchMap() {
  // Эмодзи → имена (можно несколько имен для одного эмодзи)
  const emojiNames = {
    // Smileys
    '😀': ['grinning', 'smile'],
    '😃': ['smiley', 'happy'],
    '😄': ['smile', 'joy'],
    '😁': ['grin'],
    '😆': ['laughing', 'satisfied'],
    '😅': ['sweat_smile'],
    '🤣': ['rofl', 'rolling'],
    '😂': ['joy', 'tears'],
    '🙂': ['slightly_smiling'],
    '🙃': ['upside_down'],
    '😉': ['wink'],
    '😊': ['blush'],
    '😇': ['innocent', 'angel'],
    '🥰': ['smiling_face_with_hearts', 'love'],
    '😍': ['heart_eyes', 'love'],
    '🤩': ['star_struck', 'starstruck'],
    '😘': ['kissing_heart'],
    '😗': ['kissing'],
    '☺️': ['relaxed'],
    '😚': ['kissing_closed_eyes'],
    '😙': ['kissing_smiling_eyes'],
    '🥲': ['smiling_face_with_tear'],
    '😋': ['yum', 'yummy'],
    '😛': ['stuck_out_tongue'],
    '😜': ['stuck_out_tongue_winking_eye'],
    '🤪': ['zany_face', 'crazy'],
    '😝': ['stuck_out_tongue_closed_eyes'],
    '🤑': ['money_mouth'],
    '🤗': ['hugs', 'hugging'],
    '🤭': ['hand_over_mouth'],
    '🤫': ['shushing_face', 'shh'],
    '🤔': ['thinking'],
    '🤐': ['zipper_mouth'],
    '🤨': ['raised_eyebrow'],
    '😐': ['neutral_face'],
    '😑': ['expressionless'],
    '😶': ['no_mouth'],
    '😏': ['smirk'],
    '😒': ['unamused'],
    '🙄': ['roll_eyes'],
    '😬': ['grimacing'],
    '🤥': ['lying_face', 'pinocchio'],
    '😌': ['relieved'],
    '😔': ['pensive'],
    '😪': ['sleepy'],
    '🤤': ['drooling_face', 'drool'],
    '😴': ['sleeping', 'zzz'],
    '😷': ['mask'],
    '🤒': ['face_with_thermometer', 'sick'],
    '🤕': ['face_with_head_bandage', 'injured'],
    '🤢': ['nauseated_face', 'sick'],
    '🤮': ['vomiting_face', 'puke'],
    '🤧': ['sneezing_face'],
    '🥵': ['hot_face'],
    '🥶': ['cold_face'],
    '🥴': ['woozy_face'],
    '😵': ['dizzy_face'],
    '🤯': ['exploding_head', 'mindblown'],
    '🤠': ['cowboy'],
    '🥳': ['partying_face', 'party'],
    '🥸': ['disguised_face'],
    '😎': ['sunglasses', 'cool'],
    '🤓': ['nerd_face', 'nerd'],
    '🧐': ['monocle_face'],
    
    // Negative emotions
    '😕': ['confused'],
    '😟': ['worried'],
    '🙁': ['slightly_frowning_face'],
    '☹️': ['frowning_face'],
    '😮': ['open_mouth'],
    '😯': ['hushed'],
    '😲': ['astonished'],
    '😳': ['flushed'],
    '🥺': ['pleading_face'],
    '😦': ['frowning'],
    '😧': ['anguished'],
    '😨': ['fearful'],
    '😰': ['cold_sweat'],
    '😥': ['disappointed_relieved'],
    '😢': ['cry', 'sad'],
    '😭': ['sob', 'crying'],
    '😱': ['scream'],
    '😖': ['confounded'],
    '😣': ['persevere'],
    '😞': ['disappointed'],
    '😓': ['sweat'],
    '😩': ['weary'],
    '😫': ['tired_face'],
    '🥱': ['yawning_face', 'yawn'],
    '😤': ['triumph'],
    '😡': ['rage', 'angry'],
    '😠': ['angry'],
    '🤬': ['cursing_face'],
    
    // Creatures
    '😈': ['smiling_imp'],
    '👿': ['imp'],
    '💀': ['skull'],
    '☠️': ['skull_and_crossbones'],
    '💩': ['poop', 'shit'],
    '🤡': ['clown_face'],
    '👹': ['japanese_ogre'],
    '👺': ['japanese_goblin'],
    '👻': ['ghost'],
    '👽': ['alien'],
    '👾': ['space_invader'],
    '🤖': ['robot'],
    
    // Cat faces
    '😺': ['smiley_cat'],
    '😸': ['smile_cat'],
    '😹': ['joy_cat'],
    '😻': ['heart_eyes_cat'],
    '😼': ['smirk_cat'],
    '😽': ['kissing_cat'],
    '🙀': ['scream_cat'],
    '😿': ['crying_cat_face'],
    '😾': ['pouting_cat'],
    
    // Gestures
    '👋': ['wave'],
    '🤚': ['raised_back_of_hand'],
    '🖐️': ['raised_hand_with_fingers_splayed'],
    '✋': ['hand', 'raised_hand'],
    '🖖': ['vulcan_salute', 'spock'],
    '👌': ['ok_hand'],
    '🤌': ['pinched_fingers'],
    '🤏': ['pinching_hand'],
    '✌️': ['v', 'peace'],
    '🤞': ['crossed_fingers', 'fingers_crossed'],
    '🤟': ['love_you_gesture'],
    '🤘': ['metal', 'horns'],
    '🤙': ['call_me_hand'],
    '👈': ['point_left'],
    '👉': ['point_right'],
    '👆': ['point_up_2'],
    '🖕': ['middle_finger'],
    '👇': ['point_down'],
    '☝️': ['point_up'],
    '👍': ['thumbsup', '+1'],
    '👎': ['thumbsdown', '-1'],
    '✊': ['fist'],
    '👊': ['facepunch', 'punch'],
    '🤛': ['fist_left'],
    '🤜': ['fist_right'],
    '👏': ['clap'],
    '🙌': ['raised_hands'],
    '👐': ['open_hands'],
    '🤲': ['palms_up_together'],
    '🤝': ['handshake'],
    '🙏': ['pray', 'thanks'],
    
    // Animals
    '🐶': ['dog'],
    '🐱': ['cat'],
    '🐭': ['mouse'],
    '🐹': ['hamster'],
    '🐰': ['rabbit'],
    '🦊': ['fox'],
    '🐻': ['bear'],
    '🐼': ['panda'],
    '🐨': ['koala'],
    '🐯': ['tiger'],
    '🦁': ['lion'],
    '🐮': ['cow'],
    '🐷': ['pig'],
    '🐸': ['frog'],
    '🐵': ['monkey'],
    '🙈': ['see_no_evil'],
    '🙉': ['hear_no_evil'],
    '🙊': ['speak_no_evil'],
    '🐔': ['chicken'],
    '🐧': ['penguin'],
    '🐦': ['bird'],
    '🦆': ['duck'],
    '🦅': ['eagle'],
    '🦉': ['owl'],
    '🦇': ['bat'],
    '🐺': ['wolf'],
    '🐗': ['boar'],
    '🐴': ['horse'],
    '🦄': ['unicorn'],
    '🐝': ['bee'],
    '🐛': ['bug'],
    '🦋': ['butterfly'],
    '🐌': ['snail'],
    '🐞': ['ladybug'],
    '🐜': ['ant'],
    '🕷️': ['spider'],
    '🐢': ['turtle'],
    '🐍': ['snake'],
    '🦎': ['lizard'],
    '🦖': ['t-rex', 'trex'],
    '🦕': ['sauropod', 'dinosaur'],
    '🐙': ['octopus'],
    '🦑': ['squid'],
    '🦐': ['shrimp'],
    '🦞': ['lobster'],
    '🦀': ['crab'],
    '🐡': ['blowfish'],
    '🐠': ['tropical_fish'],
    '🐟': ['fish'],
    '🐬': ['dolphin'],
    '🐳': ['whale'],
    '🐋': ['whale2'],
    '🦈': ['shark'],
    '🐊': ['crocodile'],
    '🐅': ['tiger2'],
    '🐆': ['leopard'],
    '🦓': ['zebra'],
    '🦍': ['gorilla'],
    '🦧': ['orangutan'],
    '🐘': ['elephant'],
    '🦛': ['hippopotamus'],
    '🦏': ['rhinoceros'],
    '🐪': ['camel'],
    '🐫': ['dromedary_camel'],
    '🦒': ['giraffe'],
    '🦘': ['kangaroo'],
    '🐃': ['water_buffalo'],
    '🐂': ['ox'],
    '🐄': ['cow2'],
    '🐎': ['racehorse'],
    '🐖': ['pig2'],
    '🐏': ['ram'],
    '🐑': ['sheep'],
    '🦙': ['llama'],
    '🐐': ['goat'],
    '🦌': ['deer'],
    '🐕': ['dog2'],
    '🐩': ['poodle'],
    '🐈': ['cat2'],
    '🐓': ['rooster'],
    '🦃': ['turkey'],
    '🦚': ['peacock'],
    '🦜': ['parrot'],
    
    // Food
    '🍇': ['grapes'],
    '🍈': ['melon'],
    '🍉': ['watermelon'],
    '🍊': ['tangerine', 'orange'],
    '🍋': ['lemon'],
    '🍌': ['banana'],
    '🍍': ['pineapple'],
    '🥭': ['mango'],
    '🍎': ['apple'],
    '🍏': ['green_apple'],
    '🍐': ['pear'],
    '🍑': ['peach'],
    '🍒': ['cherries'],
    '🍓': ['strawberry'],
    '🥝': ['kiwi_fruit'],
    '🍅': ['tomato'],
    '🥑': ['avocado'],
    '🍆': ['eggplant'],
    '🥔': ['potato'],
    '🥕': ['carrot'],
    '🌽': ['corn'],
    '🌶️': ['hot_pepper'],
    '🥒': ['cucumber'],
    '🥦': ['broccoli'],
    '🍄': ['mushroom'],
    '🥜': ['peanuts'],
    '🌰': ['chestnut'],
    '🍞': ['bread'],
    '🥐': ['croissant'],
    '🥖': ['baguette_bread'],
    '🥨': ['pretzel'],
    '🥯': ['bagel'],
    '🥞': ['pancakes'],
    '🧇': ['waffle'],
    '🧀': ['cheese'],
    '🍖': ['meat_on_bone'],
    '🍗': ['poultry_leg'],
    '🥩': ['cut_of_meat', 'steak'],
    '🥓': ['bacon'],
    '🍔': ['hamburger', 'burger'],
    '🍟': ['fries', 'french_fries'],
    '🍕': ['pizza'],
    '🌭': ['hotdog', 'hot_dog'],
    '🥪': ['sandwich'],
    '🌮': ['taco'],
    '🌯': ['burrito'],
    '🥙': ['stuffed_flatbread'],
    '🧆': ['falafel'],
    '🥚': ['egg'],
    '🍳': ['fried_egg', 'cooking'],
    '🥘': ['shallow_pan_of_food', 'paella'],
    '🍲': ['stew'],
    '🥣': ['bowl_with_spoon'],
    '🥗': ['green_salad', 'salad'],
    '🍿': ['popcorn'],
    '🧈': ['butter'],
    '🧂': ['salt'],
    '🍱': ['bento'],
    '🍘': ['rice_cracker'],
    '🍙': ['rice_ball'],
    '🍚': ['rice'],
    '🍛': ['curry'],
    '🍜': ['ramen'],
    '🍝': ['spaghetti', 'pasta'],
    '🍠': ['sweet_potato'],
    '🍢': ['oden'],
    '🍣': ['sushi'],
    '🍤': ['fried_shrimp'],
    '🍥': ['fish_cake'],
    '🥮': ['moon_cake'],
    '🍡': ['dango'],
    '🥟': ['dumpling'],
    '🥠': ['fortune_cookie'],
    '🥡': ['takeout_box'],
    '🦀': ['crab'],
    '🦞': ['lobster'],
    '🦐': ['shrimp'],
    '🦑': ['squid'],
    '🦪': ['oyster'],
    '🍦': ['icecream', 'ice_cream'],
    '🍧': ['shaved_ice'],
    '🍨': ['ice_cream'],
    '🍩': ['doughnut', 'donut'],
    '🍪': ['cookie'],
    '🎂': ['birthday', 'cake'],
    '🍰': ['cake'],
    '🧁': ['cupcake'],
    '🥧': ['pie'],
    '🍫': ['chocolate_bar'],
    '🍬': ['candy'],
    '🍭': ['lollipop'],
    '🍮': ['custard'],
    '🍯': ['honey_pot'],
    
    // Drinks
    '🍼': ['baby_bottle'],
    '🥛': ['milk_glass', 'milk'],
    '☕': ['coffee'],
    '🍵': ['tea'],
    '🍶': ['sake'],
    '🍾': ['champagne'],
    '🍷': ['wine_glass'],
    '🍸': ['cocktail'],
    '🍹': ['tropical_drink'],
    '🍺': ['beer'],
    '🍻': ['beers'],
    '🥂': ['clinking_glasses'],
    '🥃': ['tumbler_glass', 'whisky'],
    '🥤': ['cup_with_straw'],
    '🧃': ['beverage_box'],
    '🧉': ['mate'],
    '🧊': ['ice_cube'],
    
    // Hearts
    '❤️': ['heart', 'red_heart'],
    '🧡': ['orange_heart'],
    '💛': ['yellow_heart'],
    '💚': ['green_heart'],
    '💙': ['blue_heart'],
    '💜': ['purple_heart'],
    '🖤': ['black_heart'],
    '🤍': ['white_heart'],
    '🤎': ['brown_heart'],
    '💔': ['broken_heart'],
    '❣️': ['heavy_heart_exclamation'],
    '💕': ['two_hearts'],
    '💞': ['revolving_hearts'],
    '💓': ['heartbeat'],
    '💗': ['heartpulse'],
    '💖': ['sparkling_heart'],
    '💘': ['cupid'],
    '💝': ['gift_heart'],
    
    // Common symbols
    '✅': ['white_check_mark', 'check'],
    '❌': ['x', 'cross'],
    '⭕': ['o'],
    '💯': ['100'],
    '🔥': ['fire'],
    '⚡': ['zap', 'lightning'],
    '✨': ['sparkles'],
    '💥': ['boom'],
    '💫': ['dizzy'],
    '💬': ['speech_balloon'],
    '💭': ['thought_balloon'],
    '👀': ['eyes'],
    '🔴': ['red_circle'],
    '🟠': ['orange_circle'],
    '🟡': ['yellow_circle'],
    '🟢': ['green_circle'],
    '🔵': ['blue_circle'],
    '🟣': ['purple_circle'],
    '⚪': ['white_circle'],
    '⚫': ['black_circle'],
    '🟤': ['brown_circle'],
  };

  // Создаём Map: name → emoji
  const map = new Map();
  
  for (const [emoji, names] of Object.entries(emojiNames)) {
    names.forEach(name => {
      map.set(name, emoji);
    });
  }

  return map;
}